# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CFBmULRpvSIranUfrJnUVWt-ibHA7ekP
"""

import pandas as pd
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

"""Пример"""

pd.get_dummies(data['whoAmI'])

"""Задача 44: В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего
из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без
get_dummies?
"""

data.loc[data['whoAmI']=='robot','robot'] = '1'
data.loc[data['whoAmI']=='human','human'] = '1'
null = data.fillna('0')
null